#pragma once
#include <iostream>
#include <GLFW/glfw3.h>
#include <fstream>
#include <future>
#include <Windows.h>
#include "dataclass.h"
#include "pythago.h"
integertrans trasfer;
#include "visualwindow.h"
#include "helppages.h"
#include <string.h>
